#!/usr/bin/env node
// Generate the Homebrew formula for a release, with the real checksums, for
// supercorp-ai/homebrew-tap:
//
//   brew install supercorp-ai/tap/supergateway
//
// Apple Silicon Macs and Linux get the standalone executable from the GitHub
// release, so nothing else is installed. Node cannot build one for Intel Macs,
// so there the formula installs the npm package on Homebrew's Node, the way
// homebrew-core installs Node CLIs. Either way the command is `supergateway`.
//
// A formula carries a sha256 per platform, which changes every release, so it
// is generated rather than edited. The npm package has to be published first.
//
// Usage: node scripts/brew-formula.mjs [version]  (defaults to package.json)
import { createHash } from 'node:crypto'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const repository = resolve(import.meta.dirname, '..')
const version =
  process.argv[2] ??
  JSON.parse(readFileSync(resolve(repository, 'package.json'), 'utf8')).version
const release = `https://github.com/supercorp-ai/supergateway/releases/download/v${version}`

// Homebrew runs on macOS and glibc Linux; the musl and Windows executables
// have no formula.
const platforms = [
  {
    block: 'on_macos',
    cpu: 'on_arm',
    url: `${release}/supergateway-darwin-arm64.tar.gz`,
  },
  {
    block: 'on_macos',
    cpu: 'on_intel',
    url: `https://registry.npmjs.org/supergateway/-/supergateway-${version}.tgz`,
    comment:
      '# Node cannot build a standalone executable for Intel Macs, so they get\n' +
      "      # the npm package on Homebrew's Node.",
    dependsOn: 'node',
  },
  {
    block: 'on_linux',
    cpu: 'on_arm',
    url: `${release}/supergateway-linux-arm64.tar.gz`,
  },
  {
    block: 'on_linux',
    cpu: 'on_intel',
    url: `${release}/supergateway-linux-x64.tar.gz`,
  },
]

async function checksum(url) {
  const response = await fetch(url, { redirect: 'follow' })
  if (!response.ok) throw new Error(`${url}: ${response.status}`)
  return createHash('sha256')
    .update(Buffer.from(await response.arrayBuffer()))
    .digest('hex')
}

for (const platform of platforms) platform.sha256 = await checksum(platform.url)

const section = (block) => {
  const inner = platforms
    .filter((platform) => platform.block === block)
    .map(
      (platform) =>
        `    ${platform.cpu} do\n` +
        (platform.comment ? `      ${platform.comment}\n` : '') +
        `      url "${platform.url}"\n` +
        `      sha256 "${platform.sha256}"\n` +
        (platform.dependsOn
          ? `      depends_on "${platform.dependsOn}"\n`
          : '') +
        `    end`,
    )
    .join('\n\n')
  return `  ${block} do\n${inner}\n  end`
}

process.stdout
  .write(`# Generated by supercorp-ai/supergateway's scripts/brew-formula.mjs. Do not edit by hand.
class Supergateway < Formula
  desc "Run MCP stdio servers over SSE, WebSockets or Streamable HTTP, and back"
  homepage "https://github.com/supercorp-ai/supergateway"
  version "${version}"
  license "MIT"

${section('on_macos')}

${section('on_linux')}

  def install
    if OS.mac? && Hardware::CPU.intel?
      system "npm", "install", *std_npm_args
      bin.install_symlink libexec.glob("bin/*")
    else
      bin.install "supergateway"
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/supergateway --version")
  end
end
`)
